image:
  file: .gitpod.Dockerfile

tasks:
  - name: nix-daemon
    command: |
      sudo -E PATH="$PATH" nix daemon
  - name: db
    command: |
      sudo -E PATH="$PATH" ./db.sh
  - name: tailscale
    command: |
      sudo -E PATH="$PATH" ./tail.sh
github: 
  prebuilds:
    # enable for the default branch
    master: true
