image:
  file: .gitpod.Dockerfile

tasks:
  - name: db
    command: |
      ./db.sh
  - name: tailscale
    command: |
      ./tail.sh
github: 
  prebuilds:
    # enable for the default branch
    master: true
